CREATE TABLE IF NOT EXISTS songs(  
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT
);

CREATE TABLE IF NOT EXISTS hashs(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    song_id INTEGER,
    freq1 INTEGER,
    freq2 INTEGER,
    delta INTEGER,
    time INTEGER,
    FOREIGN KEY (song_id) REFERENCES songs(id)
);

CREATE INDEX IF NOT EXISTS hash_index
ON hashs(freq1, freq2, delta);